arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

major_minor_ver:
  - 9.2
  - 10.0
  - 10.1
  - 10.2
  - 11.0
  - 11.1
  - 11.2.2
  - 11.3.1
  - 11.4.2
  - 11.5.1
  - 11.6.0
  - 11.7.0

cuda_compiler_version:                          # [linux64]
  - None                                        # [linux64]
docker_image:                                   # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux64]
cudnn:                                          # [linux64]
  - undefined                                   # [linux64]
cdt_name:                                       # [linux64]
  - cos7                                        # [linux64]
